
# import os
# from src.ml.inference import TireDegradationPredictor
# from src.ingestion.loader import F1DataLoader
# from src.vectordb.vector_store import F1VectorStoreManager

# def run_historical_query_pipeline(user_question: str):
#     """Pipeline designed specifically to extract historical race statistics using RAG."""
#     print("\n🔍 Analyzing historical statistical request via ChromaDB...")
#     vdb_manager = F1VectorStoreManager()
    
#     # Force seed the stats data to make sure it exists in the database rows
#     vdb_manager.add_historical_stats()
    
#     # Query ChromaDB using the raw question text
#     retrieved_stats = vdb_manager.query_similar_context(user_question, n_results=1)
    
#     prompt = f"""
#     You are an expert F1 Data Analyst. Answer the user's historical question accurately using ONLY the verified context below.
    
#     [VERIFIED HISTORICAL DATABASE CONTEXT]
#     {retrieved_stats}
    
#     [USER QUESTION]
#     {user_question}
    
#     Provide a clean, well-formatted breakdown answering the user's specific request.
#     """
    
#     from src.llm.llm_client import OpenAIEngine
#     ai_system = OpenAIEngine()
#     response = ai_system.generate_response(prompt)
    
#     print("\n======================================================================")
#     print("📊 HISTORICAL STATISTICAL BRIEFING")
#     print("======================================================================")
#     print(response)
#     print("======================================================================\n")

# def run_strategy_pipeline(circuit: str, current_lap: int, compound_choice: str, target_stint: int):
#     """Our existing ML tire simulation pipeline."""
#     print(f"\n--- [STRATEGY ENGINE] Analyzing Scenario for {circuit} ---")
    
#     loader = F1DataLoader()
#     try:
#         weather_ctx = loader.get_live_track_conditions(2024, circuit)
#         print(f"Track Status: Temp is {weather_ctx['TrackTemp']}°C")
#     except Exception:
#         weather_ctx = {"TrackTemp": 26.2, "AirTemp": 16.0, "Rainfall": False}
#         print("Track Status: Using baseline track telemetry (26.2°C)")

#     print(f"Running ML Simulation for a {target_stint}-lap stint on {compound_choice.upper()} tires...")
#     ml_engine = TireDegradationPredictor(
#         model_path="ml_models/tire_deg_model.pkl", 
#         features_path="ml_models/model_features.pkl"
#     )
#     predictions = ml_engine.simulate_stint(current_lap, target_stint, compound_choice)
    
#     vdb_manager = F1VectorStoreManager()
#     query = "What rules apply to tire changes under a Safety Car?"
#     regulatory_rules = vdb_manager.query_similar_context(query, n_results=1)
    
#     prompt = f"Evaluate strategy given these ML parameters: {predictions} and rules: {regulatory_rules}"
    
#     from src.llm.llm_client import OpenAIEngine
#     ai_system = OpenAIEngine()
#     briefing = ai_system.generate_response(prompt)
    
#     print("\n======================================================================")
#     print("FINAL RACE STRATEGY BRIEF GENERATED BY AI")
#     print("======================================================================")
#     print(briefing)
#     print("======================================================================\n")

# if __name__ == "__main__":
#     print("======================================================================")
#     print("🏎️  WELCOME TO THE F1 INTERACTIVE ENGINE  🏎️")
#     print("======================================================================")
#     print("Options:")
#     print("1. Type 'sim' to run an ML Tire Degradation Simulation Strategy.")
#     print("2. Type a direct question to look up historical circuit records.")
#     print("----------------------------------------------------------------------")
    
#     user_choice = input("What would you like to do? (Type 'sim' or ask your question): ").strip()
    
#     if user_choice.lower() == 'sim':
#         circuit_input = input("Enter Circuit Name (e.g., Catalunya): ").strip()
        
#         # Wrapped inputs in a try-except block to completely protect against decimals/typos
#         try:
#             lap_input = int(input("Enter Current Lap Number (e.g., 1): "))
#         except ValueError:
#             print("⚠️ Invalid lap number. Defaulting to Lap 1.")
#             lap_input = 1
            
#         try:
#             # We convert to a float first, then to an int, so even if you type '4.657', it will round down to 4 instead of crashing!
#             raw_stint = input("Enter Simulation Stint Length (Number of Laps, e.g., 12): ")
#             stint_input = int(float(raw_stint))
#             if stint_input <= 0:
#                 raise ValueError
#         except ValueError:
#             print("⚠️ Invalid stint length number of laps. Defaulting to a 12-lap stint.")
#             stint_input = 12
            
#         compound_input = input("Enter Target Compound (SOFT/MEDIUM/HARD): ").strip().upper()
#         if compound_input not in ["SOFT", "MEDIUM", "HARD"]:
#             print("⚠️ Unknown compound. Defaulting to MEDIUM.")
#             compound_input = "MEDIUM"
        
#         run_strategy_pipeline(circuit_input, lap_input, compound_input, stint_input)
#     else:
#         # Treat the entire string input as an open historical question for our RAG database
#         run_historical_query_pipeline(user_choice)
        
#     print("\n--- Pipeline Execution Completed Successfully ---")


#     def run_historical_query_pipeline(user_question: str, target_url: str = None):
#         vdb_manager = F1VectorStoreManager()
    
#     # If the user supplied an official web URL link, dynamically fetch and store it right now!
#     if target_url:
#         print(f"\n🚀 [AUTOMATION ACTIVATED] Live data synchronizer triggered...")
#         vdb_manager.ingest_live_web_data(url=target_url, source_id="live_feed_ingest")
    
#     print("\n🔍 Querying local ChromaDB rows for your answer context...")
#     retrieved_stats = vdb_manager.query_similar_context(user_question, n_results=2)
    
#     prompt = f"""
#     You are an expert F1 Data Analyst. Answer the user's question using ONLY the verified context below.
    
#     [VERIFIED DATABASE CONTEXT]
#     {retrieved_stats}
    
#     [USER QUESTION]
#     {user_question}
    
#     Provide a clean, engineering-focused layout response.
#     """
    
#     from src.llm.llm_client import OpenAIEngine
#     ai_system = OpenAIEngine()
#     response = ai_system.generate_response(prompt)
    
#     print("\n======================================================================")
#     print("📊 DYNAMIC F1 LIVE ENGINE REPORT")
#     print("======================================================================")
#     print(response)
#     print("======================================================================\n")

# if __name__ == "__main__":
#     print("======================================================================")
#     print("🏎️  WELCOME TO THE F1 INTERACTIVE ENGINE  🏎️")
#     print("======================================================================")
#     print("Options:")
#     print("1. Type 'sim' to run an ML Tire Degradation Simulation Strategy.")
#     print("2. Type 'web' to scrape a live F1 URL page and index it into the database.")
#     print("----------------------------------------------------------------------")
    
#     user_choice = input("What would you like to do? (Type 'sim' or 'web'): ").strip().lower()
    
#     if user_choice == 'sim':
#         circuit_input = input("Enter Circuit Name: ").strip()
#         try:
#             lap_input = int(input("Enter Current Lap Number (e.g., 1): "))
#         except ValueError:
#             lap_input = 1
#         try:
#             raw_stint = input("Enter Simulation Stint Length (Number of Laps): ")
#             stint_input = int(float(raw_stint))
#         except ValueError:
#             stint_input = 12
#         compound_input = input("Enter Target Compound (SOFT/MEDIUM/HARD): ").strip().upper()
#         run_strategy_pipeline(circuit_input, lap_input, compound_input, stint_input)
        
#     elif user_choice == 'web':
#         # Prompting for inputs sequentially 
#         url_input = input("Paste the F1 URL you want to ingest: ").strip()
#         question_input = input("What specific question do you want to ask about this webpage? ").strip()
        
#         # Passes variables straight into the pipeline safely
#         run_historical_query_pipeline(user_question=question_input, target_url=url_input)
        
#     else:
#         print("⚠️ Invalid menu selection. Closing pipeline.")
        
#     print("\n--- Pipeline Execution Completed Successfully ---")


import os

def run_historical_query_pipeline(user_question: str, target_url: str = None):
    from src.vectordb.vector_store import F1VectorStoreManager
    """Pipeline designed to answer historical or single-page web questions."""
    vdb_manager = F1VectorStoreManager()

    if target_url:
        print(f"\n🚀 [AUTOMATION ACTIVATED] Live data scraping synchronizer triggered...")
        vdb_manager.ingest_live_web_data(url=target_url, source_id="live_feed_ingest")
    else:
        vdb_manager.add_historical_stats()

    print("\n🔍 Querying local ChromaDB rows for your answer context...")
    retrieved_stats, metadata = vdb_manager.query_similar_context(user_question, n_results=5)
    
    # Show sources used for transparency
    print(f"\n📍 Sources retrieved: {len(metadata)} context blocks")
    for meta in metadata:
        source = meta.get('source_url') or meta.get('source', 'unknown')
        print(f"   - {source}")

    prompt = f"""
======================================================================
SYSTEM CONTEXT FOR HISTORICAL DATA ANALYST
======================================================================
You are an expert F1 Data Analyst. Answer the user's question using ONLY the verified context below.
Prioritize the content from the scraped page and avoid returning unrelated historical summaries.
If the requested year or specific prediction information is not present, say so clearly and summarize the nearest relevant information.

[VERIFIED DATABASE CONTEXT]
{retrieved_stats}

[USER QUESTION]
{user_question}

Provide a clean, engineering-focused layout response.
"""
    
    from src.llm.llm_client import OpenAIEngine
    ai_system = OpenAIEngine()
    response = ai_system.generate_response(prompt)
    
    print("\n======================================================================")
    print("📊 DYNAMIC F1 LIVE ENGINE REPORT")
    print("======================================================================")
    print(response)
    print("======================================================================\n")
    return {"strategy_briefing": response, "constructed_prompt": prompt}

def run_web_interactive_session(url: str):
    from src.vectordb.vector_store import F1VectorStoreManager
    from src.llm.llm_client import OpenAIEngine

    vdb_manager = F1VectorStoreManager()
    print(f"\n🚀 [AUTOMATION ACTIVATED] Live data scraping synchronizer triggered...")
    vdb_manager.ingest_live_web_data(url=url, source_id="live_feed_ingest")
    print("\n✅ Live page indexed. You can now ask multiple questions about this content.")
    print("Type 'quit' or 'exit' to stop the session.")

    ai_system = OpenAIEngine()
    while True:
        user_question = input("\nAsk a question about the scraped page: ").strip()
        if not user_question:
            continue
        if user_question.lower() in {"quit", "exit", "q"}:
            print("\n👋 Ending the interactive web session.")
            break

        print("\n🔍 Querying local ChromaDB rows for your answer context...")
        retrieved_stats, metadata = vdb_manager.query_similar_context(user_question, n_results=5)
        
        # Show sources used for transparency
        print(f"\n📍 Sources retrieved: {len(metadata)} context blocks")
        for meta in metadata:
            source = meta.get('source_url') or meta.get('source', 'unknown')
            print(f"   - {source}")

        prompt = f"""
======================================================================
SYSTEM CONTEXT FOR LIVE WEB DATA ANALYST
======================================================================
You are an expert F1 Data Analyst. Answer the user's question using ONLY the verified context below.
Prioritize the content from the scraped page and avoid returning unrelated historical summaries.
If the requested prediction or strategy detail is not present, state that clearly and summarize the nearest relevant information.

[VERIFIED DATABASE CONTEXT]
{retrieved_stats}

[USER QUESTION]
{user_question}

Provide a clean, engineering-focused layout response.
"""

        response = ai_system.generate_response(prompt)
        print("\n======================================================================")
        print("📊 DYNAMIC F1 LIVE ENGINE REPORT")
        print("======================================================================")
        print(response)
        print("======================================================================")

    return


def run_strategy_pipeline(circuit: str, current_lap: int, compound_choice: str, target_stint: int):
    """Our existing ML tire simulation pipeline."""
    print(f"\n--- [STRATEGY ENGINE] Analyzing Scenario for {circuit} ---")

    from src.ml.inference import TireDegradationPredictor
    from src.ingestion.loader import F1DataLoader
    from src.vectordb.vector_store import F1VectorStoreManager

    loader = F1DataLoader()
    try:
        weather_ctx = loader.get_live_track_conditions(2024, circuit)
        print(f"Track Status: Temp is {weather_ctx['TrackTemp']}°C | Ambient is {weather_ctx['AirTemp']}°C")
    except Exception:
        weather_ctx = {"TrackTemp": 26.2, "AirTemp": 16.0, "Rainfall": False}
        print("Track Status: Using baseline track telemetry (26.2°C)")

    print(f"Running ML Simulation for a {target_stint}-lap stint on {compound_choice.upper()} tires...")
    ml_engine = TireDegradationPredictor(
        model_path="ml_models/tire_deg_model.pkl",
        features_path="ml_models/model_features.pkl"
    )
    predictions = ml_engine.simulate_stint(current_lap, target_stint, compound_choice)
    
    # Print out the first few simulated laps
    for lap_info in predictions[:3]:
        print(f"  -> Simulated Lap {current_lap + lap_info['Lap']}: Projected Laptime = {lap_info['PredictedLapTime']}s")
    print(f"  -> ... Simulating down to Lap {current_lap + target_stint} ...")
    
    vdb_manager = F1VectorStoreManager()
    query = "What rules apply to tire changes under a Safety Car?"
    regulatory_rules = vdb_manager.query_similar_context(query, n_results=1)
    
    prompt = f"""
======================================================================
SYSTEM CONTEXT FOR RACE STRATEGIST AI
======================================================================
You are the Lead Race Strategist for Scuderia Ferrari. Analyze the following race scenario:

[LIVE TELEMETRY DATA]
Circuit: {circuit}
Track Temperature: {weather_ctx['TrackTemp']}°C
Current Strategic Lap Marker: Lap {current_lap}

[ML MODEL DEGRADATION SIMULATIONS]
Target Compound Evaluation: {compound_choice.upper()}
Predicted Lap-by-Lap Times (Seconds) over the next {target_stint} laps:
{predictions}

[RETRIEVED FIA SPORTING CODES]
{regulatory_rules}

======================================================================
INSTRUCTIONS
======================================================================
Write a highly concise technical race strategy brief for the team principal. 
1. Evaluate the tire degradation slope shown in the ML metrics.
2. Cross-reference the retrieved FIA rules to confirm if a pitstop execution under these conditions is legal and strategically optimal.
3. Keep it engineering-focused and brief.
"""
    
    from src.llm.llm_client import OpenAIEngine
    ai_system = OpenAIEngine()
    briefing = ai_system.generate_response(prompt)
    
    print("\n======================================================================")
    print("FINAL RACE STRATEGY BRIEF GENERATED BY AI")
    print("======================================================================")
    print(briefing)
    print("======================================================================\n")
    return {"simulation_data": predictions, "strategy_briefing": briefing, "constructed_prompt": prompt}

if __name__ == "__main__":
    print("======================================================================")
    print("🏎️  WELCOME TO THE F1 INTERACTIVE ENGINE  🏎️")
    print("======================================================================")
    print("Options:")
    print("1. Type 'sim' to run an ML Tire Degradation Simulation Strategy.")
    print("2. Type 'web' to scrape a live F1 URL page and index it into the database.")
    print("----------------------------------------------------------------------")
    
    user_choice = input("What would you like to do? (Type 'sim' or 'web'): ").strip().lower()
    
    if user_choice == 'sim':
        circuit_input = input("Enter Circuit Name: ").strip()
        try:
            lap_input = int(input("Enter Current Lap Number (e.g., 1): "))
        except ValueError:
            lap_input = 1
        try:
            raw_stint = input("Enter Simulation Stint Length (Number of Laps): ")
            stint_input = int(float(raw_stint))
        except ValueError:
            stint_input = 12
        compound_input = input("Enter Target Compound (SOFT/MEDIUM/HARD): ").strip().upper()
        run_strategy_pipeline(circuit_input, lap_input, compound_input, stint_input)
        
    elif user_choice == 'web':
        url_input = input("Paste the F1 URL you want to ingest: ").strip()
        run_web_interactive_session(url_input)
        
    else:
        print("⚠️ Invalid menu selection. Closing pipeline.")
        
    print("\n--- Pipeline Execution Completed Successfully ---")